name: ani_verse
description: "Aime app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  json_annotation: ^4.9.0
  path_provider: ^2.0.11
  result_dart: ^2.0.0
  provider: ^6.1.2
  go_router: ^14.6.3
  shared_preferences: ^2.3.5
  get_it: ^8.0.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner:

flutter:
  uses-material-design: true